name: wowowwish

description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.3.7
label: wowow许愿啦
environment:
  sdk: '>=3.0.6 <4.0.0'
#
dependencies:

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_isolate:
  flutter_local_notifications: ^15.1.1
  get: ^4.6.5
  avatar_glow: ^2.0.2
  adaptive_dialog: ^1.9.0
  fluttertoast: ^8.2.2
  dio:
  image_picker: ^1.0.2
  get_storage:
  bottom_sheet: ^3.1.2
  image_cropper: ^5.0.0
  yaml:
  auto_animated:
  permission_handler:
  flutter_easyloading:
  path_provider:
  flutter_svg:
  image_gallery_saver:
  photo_view:
  encrypt:
  animated_text_kit:
  cached_network_image:
  harmony_plugin: ^0.1.0
  harmonyos: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NotoSansSc
      fonts:
        - asset: assets/fonts/noto_sans_sc/NotoSansSC-Thin.ttf
          weight: 100
        - asset: assets/fonts/noto_sans_sc/NotoSansSC-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/noto_sans_sc/NotoSansSC-Light.ttf
          weight: 300
        - asset: assets/fonts/noto_sans_sc/NotoSansSC-Regular.ttf
          weight: 400
        - asset: assets/fonts/noto_sans_sc/NotoSansSC-Medium.ttf
          weight: 500
        - asset: assets/fonts/noto_sans_sc/NotoSansSC-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/noto_sans_sc/NotoSansSC-Bold.ttf
          weight: 700
        - asset: assets/fonts/noto_sans_sc/NotoSansSC-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/noto_sans_sc/NotoSansSC-Black.ttf
          weight: 900
